#!/usr/bin/env python3
"""Harness state transition validation script.

Called from Claude Code hooks to block harness rule violations.

Usage: validate_harness.py <check_type>
  check_type:
    pre-state-write  — Before writing harness_state.json: verify external evaluation exists before leaving generated
    post-state-write — After writing harness_state.json: verify status=passed <-> status_action consistency
    pre-gen          — Before Generator execution: verify contract.md exists
    post-eval        — After evaluation: verify external model verdict in issues.json
    guard-eval-files — Block direct writing of issues.json (only eval_dispatch.py allowed)
    pre-commit       — Run tests before commit (only in harness mode)
    pre-push         — Run tests + verify state consistency before push
"""

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

HARNESS_DIR = Path(".claude/harness")
STATE_FILE = HARNESS_DIR / "harness_state.json"


def load_json(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def load_state() -> dict:
    return load_json(STATE_FILE) or {}


def get_current_sprint(state: dict) -> str:
    idx = state.get("current_sprint_index", 0)
    sprints = state.get("sprints", [])
    if idx < len(sprints):
        return sprints[idx].get("sprint_id", "")
    return ""


def get_current_status(state: dict) -> str:
    idx = state.get("current_sprint_index", 0)
    sprints = state.get("sprints", [])
    if idx < len(sprints):
        return sprints[idx].get("status", "")
    return ""


def get_test_command() -> str:
    spec_file = HARNESS_DIR / "spec.md"
    if not spec_file.exists():
        return ""
    content = spec_file.read_text(encoding="utf-8")
    match = re.search(r'test_command:\s*"([^"]+)"', content)
    return match.group(1) if match else ""


def verify_issues_integrity(issues_file: Path) -> str:
    if not issues_file.exists():
        return "FAIL:file_not_found"
    data = load_json(issues_file)
    if data is None:
        return "FAIL:parse_error"
    required = ["evaluated_at", "models_used", "models_valid", "verdict", "model_verdicts", "status_action"]
    missing = [k for k in required if k not in data]
    if missing:
        return f"FAIL:missing_fields:{','.join(missing)}"
    if not data.get("evaluated_at", "").startswith("20"):
        return "FAIL:invalid_timestamp"
    return "OK"


def get_valid_model_count(issues_file: Path) -> int:
    data = load_json(issues_file)
    if data is None:
        return 0
    return len(data.get("models_valid", []))


def get_verdict(issues_file: Path) -> str:
    data = load_json(issues_file)
    if data is None:
        return "unknown"
    return data.get("verdict", "unknown")


def get_status_action(issues_file: Path) -> str:
    data = load_json(issues_file)
    if data is None:
        return "unknown"
    return data.get("status_action", "unknown")


def fail(msg: str) -> None:
    print(msg, file=sys.stderr)
    sys.exit(1)


def info(msg: str) -> None:
    print(msg)


# ── Check handlers ──────────────────────────────────────────────


def check_pre_state_write() -> None:
    """Validation before writing harness_state.json."""
    # Create backup for rollback (used by post-state-write)
    try:
        shutil.copy2(STATE_FILE, f"{STATE_FILE}.bak")
    except OSError:
        pass

    state = load_state()
    current_sprint = get_current_sprint(state)
    current_status = get_current_status(state)

    if not current_sprint:
        return  # No sprints yet, initialization phase
    if current_status != "generated":
        return  # Transitions from non-generated states don't require evaluation

    # State change from generated state -> external evaluation must exist
    issues_file = HARNESS_DIR / "sprints" / current_sprint / "issues.json"
    integrity = verify_issues_integrity(issues_file)

    if integrity == "FAIL:file_not_found":
        fail(
            "[HARNESS-GUARD] Blocked: Attempted transition from generated state without external evaluation\n"
            "[HARNESS-GUARD] Run eval_dispatch.py first."
        )
    if integrity.startswith("FAIL:"):
        fail(
            f"[HARNESS-GUARD] Blocked: issues.json integrity check failed: {integrity}\n"
            "[HARNESS-GUARD] This is not a valid file generated by eval_dispatch.py."
        )

    valid_count = get_valid_model_count(issues_file)
    if valid_count < 2:
        fail(
            f"[HARNESS-GUARD] Blocked: {valid_count} valid external model(s) — minimum 2 required\n"
            "[HARNESS-GUARD] Cannot transition state with single-model evaluation only."
        )

    info(f"[HARNESS-GUARD] Passed: External evaluation confirmed (valid models: {valid_count}) — state transition allowed")


def check_post_state_write() -> None:
    """Consistency check after writing harness_state.json."""
    state = load_state()
    current_sprint = get_current_sprint(state)
    current_status = get_current_status(state)
    bak = Path(f"{STATE_FILE}.bak")

    if not current_sprint or current_status != "passed":
        bak.unlink(missing_ok=True)
        return

    issues_file = HARNESS_DIR / "sprints" / current_sprint / "issues.json"
    need_rollback = False

    if not issues_file.exists():
        info("[HARNESS-GUARD] CRITICAL: status=passed but issues.json not found")
        need_rollback = True

    if not need_rollback:
        verdict = get_verdict(issues_file)
        status_action = get_status_action(issues_file)
        if status_action != "passed":
            info(f"[HARNESS-GUARD] CRITICAL: status=passed but status_action={status_action} (verdict={verdict})")
            need_rollback = True

    if need_rollback:
        if bak.exists():
            shutil.copy2(bak, STATE_FILE)
            bak.unlink(missing_ok=True)
            info("[HARNESS-GUARD] Auto-rollback complete — harness_state.json restored to previous state.")
            info("[HARNESS-GUARD] Record the correct state matching the external evaluation verdict.")
        else:
            info("[HARNESS-GUARD] Warning: No backup file — auto-rollback not possible. Manually fix harness_state.json.")
        sys.exit(1)

    bak.unlink(missing_ok=True)
    info(f"[HARNESS-GUARD] Passed: State consistency confirmed (status=passed, verdict={verdict})")


def check_guard_eval_files() -> None:
    """Block direct writing to issues.json."""
    fail(
        "[HARNESS-GUARD] Blocked: Only eval_dispatch.py can write issues.json.\n"
        "[HARNESS-GUARD] Direct creation/modification of issues.json by Claude compromises evaluation integrity.\n"
        "[HARNESS-GUARD] If external model evaluation is needed, run eval_dispatch.py via Bash."
    )


def check_pre_gen() -> None:
    """Verify contract.md exists before Generator execution."""
    state = load_state()
    current_sprint = get_current_sprint(state)
    contract = HARNESS_DIR / "sprints" / current_sprint / "contract.md"

    if not contract.exists():
        fail(
            f"[HARNESS-GUARD] Blocked: Contract not found: {contract}\n"
            "[HARNESS-GUARD] Run /ahoy:ahoy-plan first."
        )
    info("[HARNESS-GUARD] Passed: Sprint contract confirmed")


def check_post_eval() -> None:
    """Verify issues.json validity after evaluation."""
    state = load_state()
    current_sprint = get_current_sprint(state)
    issues_file = HARNESS_DIR / "sprints" / current_sprint / "issues.json"

    if not issues_file.exists():
        fail("[HARNESS-GUARD] Blocked: Evaluation result file not found")

    verdict = get_verdict(issues_file)
    status_action = get_status_action(issues_file)
    info(f"[HARNESS-GUARD] External evaluation verdict: {verdict} (status_action={status_action})")

    if verdict in ("error", "unknown"):
        data = load_json(issues_file) or {}
        reason = data.get("error_reason", "Unknown cause")
        fail(
            f"[HARNESS-GUARD] Blocked: External model evaluation failed: {reason}\n"
            "[HARNESS-GUARD] Cannot proceed without valid external model evaluation."
        )

    valid_count = get_valid_model_count(issues_file)
    if valid_count < 2:
        fail(
            f"[HARNESS-GUARD] Blocked: {valid_count} valid model(s) — minimum 2 required\n"
            "[HARNESS-GUARD] Consensus cannot be established with single-model evaluation only."
        )

    info(f"[HARNESS-GUARD] Passed: External evaluation valid (verdict: {verdict}, valid models: {valid_count})")


def check_pre_commit() -> None:
    """Run tests before commit (enforced only in harness mode)."""
    test_cmd = get_test_command()
    if not test_cmd:
        return

    info(f"[HARNESS-GUARD] Running tests before commit: {test_cmd}")
    result = subprocess.run(test_cmd, shell=True)
    if result.returncode != 0:
        fail(
            "\n[HARNESS-GUARD] Blocked: Tests failed — commit blocked\n"
            "[HARNESS-GUARD] Fix the tests and try committing again."
        )
    info("[HARNESS-GUARD] Passed: Tests passed — commit allowed")


def check_pre_push() -> None:
    """Run tests + verify harness state consistency before push."""
    # 1. Run tests
    test_cmd = get_test_command()
    if test_cmd:
        info(f"[HARNESS-GUARD] Running tests before push: {test_cmd}")
        result = subprocess.run(test_cmd, shell=True)
        if result.returncode != 0:
            fail("\n[HARNESS-GUARD] Blocked: Tests failed — push blocked")
        info("[HARNESS-GUARD] Passed: Tests passed")

    # 2. Harness state consistency check
    state = load_state()
    problems = []
    for sprint in state.get("sprints", []):
        sid = sprint.get("sprint_id", "")
        status = sprint.get("status", "")
        if status == "passed":
            issues_path = HARNESS_DIR / "sprints" / sid / "issues.json"
            if not issues_path.exists():
                problems.append(f"{sid}: passed but issues.json not found")
                continue
            data = load_json(issues_path) or {}
            verdict = data.get("verdict", "unknown")
            status_action = data.get("status_action", "unknown")
            if status_action != "passed":
                problems.append(f"{sid}: passed but status_action={status_action} (verdict={verdict})")

    if problems:
        fail(
            "[HARNESS-GUARD] Blocked: Harness state inconsistency detected:\n"
            + "\n".join(problems)
            + "\n[HARNESS-GUARD] Fix the state and try pushing again."
        )

    info("[HARNESS-GUARD] Passed: Harness state consistency confirmed — push allowed")


# ── Main ────────────────────────────────────────────────────────

CHECKS = {
    "pre-state-write": check_pre_state_write,
    "post-state-write": check_post_state_write,
    "pre-gen": check_pre_gen,
    "post-eval": check_post_eval,
    "guard-eval-files": check_guard_eval_files,
    "pre-commit": check_pre_commit,
    "pre-push": check_pre_push,
}


def main() -> None:
    # If .claude/harness doesn't exist, not in harness mode -> pass through
    if not HARNESS_DIR.is_dir() or not STATE_FILE.is_file():
        sys.exit(0)

    if len(sys.argv) < 2 or sys.argv[1] not in CHECKS:
        valid = "|".join(CHECKS)
        print(f"Usage: validate_harness.py <{valid}>")
        sys.exit(1)

    CHECKS[sys.argv[1]]()


if __name__ == "__main__":
    main()
