#!/usr/bin/env python3
"""Harness state transition validation script.

Called from Claude Code hooks to enforce Generator-Evaluator separation.

Usage: validate_harness.py <check_type>
  check_type:
    guard-eval-files     — Block direct writing of issues.json
    scope-check          — Before Edit/Write: verify target file is within contract.md Implementation Scope
    pre-gen              — Verify contract.md exists before Generator
    pre-state-write      — Require external evaluation before leaving generated
    post-eval            — Verify external model verdict in issues.json
    post-state-write     — Consistency rollback if status/verdict mismatch
    circuit-breaker      — Detect repeated failure patterns across rework attempts
"""
from __future__ import annotations

import json
import os
import re
import shutil
import sys
from pathlib import Path

HARNESS_DIR = Path(".claude/harness")
STATE_FILE = HARNESS_DIR / "harness_state.json"


def load_json(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def load_state() -> dict:
    return load_json(STATE_FILE) or {}


def get_current_sprint(state: dict) -> str:
    idx = state.get("current_sprint_index", 0)
    sprints = state.get("sprints", [])
    if idx < len(sprints):
        return sprints[idx].get("sprint_id", "")
    return ""


def get_current_status(state: dict) -> str:
    idx = state.get("current_sprint_index", 0)
    sprints = state.get("sprints", [])
    if idx < len(sprints):
        return sprints[idx].get("status", "")
    return ""


def verify_issues_integrity(issues_file: Path) -> str:
    if not issues_file.exists():
        return "FAIL:file_not_found"
    data = load_json(issues_file)
    if data is None:
        return "FAIL:parse_error"
    required = ["evaluated_at", "models_used", "models_valid", "verdict", "model_verdicts", "status_action"]
    missing = [k for k in required if k not in data]
    if missing:
        return f"FAIL:missing_fields:{','.join(missing)}"
    if not data.get("evaluated_at", "").startswith("20"):
        return "FAIL:invalid_timestamp"
    return "OK"


def get_valid_model_count(issues_file: Path) -> int:
    data = load_json(issues_file)
    if data is None:
        return 0
    return len(data.get("models_valid", []))


def get_verdict(issues_file: Path) -> str:
    data = load_json(issues_file)
    if data is None:
        return "unknown"
    return data.get("verdict", "unknown")


def get_status_action(issues_file: Path) -> str:
    data = load_json(issues_file)
    if data is None:
        return "unknown"
    return data.get("status_action", "unknown")


def fail(msg: str) -> None:
    print(msg, file=sys.stderr)
    sys.exit(1)


def info(msg: str) -> None:
    print(msg)


# ── Core checks ──────────────────────────────────────────────────


def check_guard_eval_files() -> None:
    """Block direct writing to issues.json."""
    fail(
        "[HARNESS-GUARD] Blocked: Only eval_dispatch.py can write issues.json.\n"
        "[HARNESS-GUARD] Direct creation/modification of issues.json by Claude compromises evaluation integrity.\n"
        "[HARNESS-GUARD] If external model evaluation is needed, run eval_dispatch.py via Bash."
    )


def check_pre_gen() -> None:
    """Verify contract.md exists before Generator execution."""
    state = load_state()
    current_sprint = get_current_sprint(state)
    contract = HARNESS_DIR / "sprints" / current_sprint / "contract.md"

    if not contract.exists():
        fail(
            f"[HARNESS-GUARD] Blocked: Contract not found: {contract}\n"
            "[HARNESS-GUARD] Run /ahoy:ahoy-plan first."
        )
    info("[HARNESS-GUARD] Passed: Sprint contract confirmed")


def check_pre_state_write() -> None:
    """Require external evaluation before leaving generated status."""
    try:
        shutil.copy2(STATE_FILE, f"{STATE_FILE}.bak")
    except OSError:
        pass

    state = load_state()
    current_sprint = get_current_sprint(state)
    current_status = get_current_status(state)

    if not current_sprint or current_status != "generated":
        return

    issues_file = HARNESS_DIR / "sprints" / current_sprint / "issues.json"
    integrity = verify_issues_integrity(issues_file)

    if integrity == "FAIL:file_not_found":
        fail(
            "[HARNESS-GUARD] Blocked: Attempted transition from generated state without external evaluation\n"
            "[HARNESS-GUARD] Run eval_dispatch.py first."
        )
    if integrity.startswith("FAIL:"):
        fail(
            f"[HARNESS-GUARD] Blocked: issues.json integrity check failed: {integrity}\n"
            "[HARNESS-GUARD] This is not a valid file generated by eval_dispatch.py."
        )

    # Allow backpressure gate test failures to transition without model quorum
    data = load_json(issues_file)
    if data and data.get("backpressure_gate"):
        bp_type = data["backpressure_gate"].get("result_type")
        if bp_type == "test_result" and data.get("status_action") == "failed":
            info("[HARNESS-GUARD] Passed: Backpressure gate test failure — allowing state transition")
            return

    valid_count = get_valid_model_count(issues_file)
    if valid_count < 2:
        fail(
            f"[HARNESS-GUARD] Blocked: {valid_count} valid external model(s) — minimum 2 required\n"
            "[HARNESS-GUARD] Cannot transition state with single-model evaluation only."
        )

    info(f"[HARNESS-GUARD] Passed: External evaluation confirmed (valid models: {valid_count})")


def check_post_eval() -> None:
    """Verify issues.json validity after evaluation."""
    state = load_state()
    current_sprint = get_current_sprint(state)
    issues_file = HARNESS_DIR / "sprints" / current_sprint / "issues.json"

    if not issues_file.exists():
        fail("[HARNESS-GUARD] Blocked: Evaluation result file not found")

    # Check for backpressure gate results before standard checks
    data = load_json(issues_file)
    if data and data.get("backpressure_gate"):
        bp_type = data["backpressure_gate"].get("result_type")
        if bp_type == "test_result" and data.get("status_action") == "failed":
            info("[HARNESS-GUARD] Backpressure gate: tests failed — skipping model quorum check")
            return
        # infra_error has verdict=error, caught by existing verdict check below

    verdict = get_verdict(issues_file)
    status_action = get_status_action(issues_file)
    info(f"[HARNESS-GUARD] External evaluation verdict: {verdict} (status_action={status_action})")

    if verdict in ("error", "unknown"):
        data_for_err = load_json(issues_file) or {}
        reason = data_for_err.get("error_reason", "Unknown cause")
        fail(
            f"[HARNESS-GUARD] Blocked: External model evaluation failed: {reason}\n"
            "[HARNESS-GUARD] Cannot proceed without valid external model evaluation."
        )

    valid_count = get_valid_model_count(issues_file)
    if valid_count < 2:
        fail(
            f"[HARNESS-GUARD] Blocked: {valid_count} valid model(s) — minimum 2 required\n"
            "[HARNESS-GUARD] Consensus cannot be established with single-model evaluation only."
        )

    info(f"[HARNESS-GUARD] Passed: External evaluation valid (verdict: {verdict}, valid models: {valid_count})")


def check_post_state_write() -> None:
    """Consistency check after writing harness_state.json."""
    state = load_state()
    current_sprint = get_current_sprint(state)
    current_status = get_current_status(state)
    bak = Path(f"{STATE_FILE}.bak")

    if not current_sprint or current_status != "passed":
        bak.unlink(missing_ok=True)
        return

    issues_file = HARNESS_DIR / "sprints" / current_sprint / "issues.json"
    need_rollback = False

    if not issues_file.exists():
        info("[HARNESS-GUARD] CRITICAL: status=passed but issues.json not found")
        need_rollback = True

    if not need_rollback:
        verdict = get_verdict(issues_file)
        status_action = get_status_action(issues_file)
        if status_action != "passed":
            info(f"[HARNESS-GUARD] CRITICAL: status=passed but status_action={status_action} (verdict={verdict})")
            need_rollback = True

    if need_rollback:
        if bak.exists():
            shutil.copy2(bak, STATE_FILE)
            bak.unlink(missing_ok=True)
            info("[HARNESS-GUARD] Auto-rollback complete — harness_state.json restored to previous state.")
            info("[HARNESS-GUARD] Record the correct state matching the external evaluation verdict.")
        else:
            info("[HARNESS-GUARD] Warning: No backup file — auto-rollback not possible. Manually fix harness_state.json.")
        sys.exit(1)

    bak.unlink(missing_ok=True)
    info(f"[HARNESS-GUARD] Passed: State consistency confirmed (status=passed, verdict={verdict})")


# ── Scope enforcement ─────────────────────────────────────────────


def parse_scope_from_contract(contract_path: Path) -> tuple[list[str], list[str], list[str]]:
    """Parse Implementation Scope from contract.md.

    Returns (files_to_create, files_to_modify, files_to_preserve).
    """
    try:
        content = contract_path.read_text(encoding="utf-8")
    except OSError:
        return [], [], []

    create: list[str] = []
    modify: list[str] = []
    preserve: list[str] = []

    current_section: list[str] | None = None
    in_scope = False

    for line in content.splitlines():
        stripped = line.strip()

        # Detect top-level heading that ends the scope block
        if in_scope and re.match(r"^##\s+", stripped) and "Implementation Scope" not in stripped:
            break

        if re.match(r"^##\s+Implementation Scope", stripped):
            in_scope = True
            continue

        if not in_scope:
            continue

        if re.match(r"^###\s+Files to Create", stripped):
            current_section = create
            continue
        elif re.match(r"^###\s+Files to Modify", stripped):
            current_section = modify
            continue
        elif re.match(r"^###\s+Files to Preserve", stripped):
            current_section = preserve
            continue
        elif re.match(r"^###\s+", stripped):
            current_section = None
            continue

        if current_section is not None:
            match = re.match(r"^[-*]\s+`?([^`\s]+)`?", stripped)
            if match:
                current_section.append(match.group(1))

    return create, modify, preserve


def check_scope() -> None:
    """Verify target file is within contract.md Implementation Scope."""
    state = load_state()
    current_sprint = get_current_sprint(state)

    if not current_sprint:
        return  # No active sprint, pass through

    contract_path = HARNESS_DIR / "sprints" / current_sprint / "contract.md"
    if not contract_path.exists():
        return  # No contract yet, pass through

    # Get the file path from CLAUDE_TOOL_INPUT
    tool_input_raw = os.environ.get("CLAUDE_TOOL_INPUT", "")
    if not tool_input_raw:
        return  # No tool input, pass through

    try:
        tool_input = json.loads(tool_input_raw)
    except json.JSONDecodeError:
        return  # Can't parse, pass through

    file_path = tool_input.get("file_path", "")
    if not file_path:
        return

    # Normalize to forward slashes for consistent comparison
    file_path_normalized = file_path.replace("\\", "/")

    # Always allow harness files
    if ".claude/harness/" in file_path_normalized or ".claude/harness\\" in file_path:
        return

    # Parse the allowed scope
    create, modify, preserve = parse_scope_from_contract(contract_path)

    # Files to Preserve are explicitly blocked
    for p in preserve:
        p_normalized = p.replace("\\", "/")
        if file_path_normalized.endswith(p_normalized) or p_normalized in file_path_normalized:
            fail(
                f"[HARNESS-GUARD] Blocked: '{file_path}' is listed in Files to Preserve\n"
                "[HARNESS-GUARD] This file is protected by the sprint contract and must not be modified."
            )

    # Allowed files = create + modify
    allowed = create + modify
    if not allowed:
        return  # No scope defined, pass through

    for p in allowed:
        p_normalized = p.replace("\\", "/")
        if file_path_normalized.endswith(p_normalized) or p_normalized in file_path_normalized:
            return  # File is in scope

    # Check if file is part of the AHOY plugin itself — always allow
    plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT", "")
    if plugin_root:
        plugin_normalized = plugin_root.replace("\\", "/")
        if file_path_normalized.startswith(plugin_normalized):
            return

    fail(
        f"[HARNESS-GUARD] Blocked: '{file_path}' is outside the Implementation Scope\n"
        f"[HARNESS-GUARD] Allowed files: {', '.join(allowed)}\n"
        "[HARNESS-GUARD] Only create/modify files specified in the sprint contract."
    )


# ── Circuit breaker ──────────────────────────────────────────────


def _issues_signature(issues: list[dict]) -> set[str]:
    return {
        f"{issue.get('category', '').strip().lower()}::{issue.get('description', '').strip().lower()}"
        for issue in issues
    }


def check_circuit_breaker() -> None:
    """Detect repeated failure patterns across rework attempts."""
    state = load_state()
    current_sprint = get_current_sprint(state)
    if not current_sprint:
        return

    sprint_dir = HARNESS_DIR / "sprints" / current_sprint

    # Skip if the current evaluation passed
    current_issues = load_json(sprint_dir / "issues.json")
    if current_issues and current_issues.get("status_action") == "passed":
        return

    idx = state.get("current_sprint_index", 0)
    sprint_obj = state["sprints"][idx]
    current_attempt = sprint_obj.get("attempt", 0)

    # Archive current issues.json and gen_report.md
    issues_file = sprint_dir / "issues.json"
    if issues_file.exists() and current_attempt >= 1:
        backup = sprint_dir / f"issues.json.attempt-{current_attempt}"
        if not backup.exists():
            shutil.copy2(issues_file, backup)

    gen_report = sprint_dir / "gen_report.md"
    if gen_report.exists() and current_attempt >= 1:
        gen_backup = sprint_dir / f"gen_report.md.attempt-{current_attempt}"
        if not gen_backup.exists():
            shutil.copy2(gen_report, gen_backup)

    if current_attempt < 2:
        return

    # Compare current vs previous attempt issues
    if not current_issues or not isinstance(current_issues.get("issues"), list):
        return
    current_sigs = _issues_signature(current_issues["issues"])

    prev_path = sprint_dir / f"issues.json.attempt-{current_attempt - 1}"
    prev_data = load_json(prev_path)
    if not prev_data or not isinstance(prev_data.get("issues"), list):
        return
    prev_sigs = _issues_signature(prev_data["issues"])

    repeated = current_sigs & prev_sigs
    if repeated:
        descriptions = sorted(sig.split("::", 1)[-1] for sig in repeated)
        fail(
            "[HARNESS-GUARD] Blocked: Circuit breaker — repeated failure pattern detected\n"
            f"[HARNESS-GUARD]   Repeated issues: {', '.join(descriptions)}\n"
            "[HARNESS-GUARD]   The same issues appeared in consecutive attempts — further rework is unlikely to help."
        )

    info("[HARNESS-GUARD] Passed: No repeated failure pattern detected")


# ── Main ─────────────────────────────────────────────────────────

CHECKS = {
    "guard-eval-files": check_guard_eval_files,
    "scope-check": check_scope,
    "pre-gen": check_pre_gen,
    "pre-state-write": check_pre_state_write,
    "post-eval": check_post_eval,
    "post-state-write": check_post_state_write,
    "circuit-breaker": check_circuit_breaker,
}


def main() -> None:
    if not HARNESS_DIR.is_dir() or not STATE_FILE.is_file():
        sys.exit(0)

    if len(sys.argv) < 2 or sys.argv[1] not in CHECKS:
        valid = "|".join(CHECKS)
        print(f"Usage: validate_harness.py <{valid}>")
        sys.exit(1)

    CHECKS[sys.argv[1]]()


if __name__ == "__main__":
    main()
